repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.16.1
    hooks:
      - id: stylua-github
  - repo: https://github.com/lunarmodules/luacheck
    rev: v1.1.0
    hooks:
      - id: luacheck
